config/routes.rb
Rails1011::Application.routes.draw do

  devise_for :users
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end

  namespace :account do
    resources :groups
  end
  root to: "groups#index" 

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	belongs_to :owner, :class_name => "User", :foreign_key => :user_id
	
	has_many :group_users
	has_many :members, through: :group_users, source: :user

	validates :title, :presence => true

	after_create :join_owner_to_group

	def editable_by?(user)
		user && user == owner
	end

	def join_owner_to_group
		members << owner
	end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :group, :counter_cache => true
	belongs_to :author, class_name: "User", foreign_key: :user_id
	validates :content, presence: true

	def editable_by?(user)
		user && user == author
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def join!(group)
  	participated_groups << group
  end

  def quit!(group)
  	participated_groups.delete(group)
  end

  def is_member_of?(group)
  	participated_groups.include?(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
before_action :login_required

def index
	@group = current_user.participated_groups.order("posts_count ASC")
	@post = current_user.posts.order("updated_at DESC")
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
  	if current_user.blank?
  		respond_to do |format|
  			format.html {
  				authenticate_user!
  			}
  			format.js {
  				render :partial => "common/not_logined"
  			}
  			format.all {
  				head(:unauthorized)
  			}
  		end
  	end
  end

  	protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :password_confirmation) }
 		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
 	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :login_required, :only => [:edit, :update, :new, :create, :destroy]

	def index
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])
		@post = @group.posts.order("updated_at desc")
	end

	def edit
		@group = current_user.groups.find(params[:id])
	end

	def new
		@group = Group.new
	end

	def create
		@group = current_user.groups.build(group_params)
		if @group.save
			redirect_to groups_path
			flash[:notice] = "Group successfully created"
		else
			render :new
		end
	end

	def update
		@group = current_user.groups.find(params[:id])

		if @group.update(group_params)
			redirect_to groups_path
		else
			render :edit
		end
	end

	def destroy
		@group = current_user.groups.find(params[:id])
		@group.destroy
		redirect_to groups_path
	end

	def join
		@group = Group.find(params[:id])
		if !current_user.is_member_of?(@group)
			current_user.join!(@group)
		else
			flash[:notice] = "You are already a member."
		end	
		redirect_to group_path(@group)
	end

	def quit
		@group = Group.find(params[:id])
		if current_user.is_member_of?(@group)
			current_user.quit!(@group)
		else
			flash[:notice] = "You are not a member"
		end
		redirect_to group_path(@group)
	end

	private
		def group_params
			params.require(:group).permit(:title, :description)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_group
	before_action :login_required, :only => [:edit, :update, :new, :create, :destroy]
	before_action :member_required, :only => [:new, :edit, :destroy]

	def new
		@post = @group.posts.build
	end

	def create
		@post = current_user.posts.new(post_params)
		@post.author = current_user
		@post.group = @group
		#don't know why need this line to save group_id attribute
		if @post.save
			redirect_to group_path(@group)
		else
			render :new
		end
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def update
		@post = current_user.posts.find(params[:id])
		if @post.update(post_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def destroy
		@post = current_user.posts.find(params[:id])
		@post.destroy
		redirect_to group_path(@group)
	end

	private
	def post_params
		params.require(:post).permit(:content)
	end

	def set_group
		@group = Group.find(params[:group_id])	
	end

	def member_required
		if !current_user.is_member_of?(@group)
			flash[:notice] = "You're not a member of this group"
			redirect_to group_path(@group)
		end
	end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/_join_or_quit.html.erb
<% if current_user %>
	<% if !current_user.is_member_of?(@group)%>
		<%= link_to "Join", join_group_path(@group), method: :post, :class => "btn btn-primary" %>
	<% else %>
		<%= link_to "Quit", quit_group_path(@group), method: :post, :class => "btn btn-primary" %>
	<% end %>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= simple_form_for(@group, :html => {:class => 'form-horizontal'}) do |f| %>

	<%= f.input :title, :input_html => {:class => "input-xxlarge"} %>
	<%= f.input :description %>
	<%= f.submit "Submit", :disable_with => "Submitting..." ,:class => "btn btn-primary" %>

<% end %>

app/views/groups/index.html.erb
<h1> Groups </h1>
<%= link_to "New Group", new_group_path, :class => "btn btn-primary" %>
<% @groups.each do |f| %>
	<div class="group-block">
	<p style="font-size: 20px"><strong>
	<%= link_to f.title, group_path(f) %>
	</strong><% if current_user && f.editable_by?(current_user)%>(<%= link_to "edit", edit_group_path(f) %> | <%= link_to "Delete", group_path(f) , method: :delete, :confirm => "Are you sure?" %>)</p><% end %>
	<p><%= f.description %></p>
	</div>
<% end %>

app/views/groups/new.html.erb
<h1>Creating New Group</h1>

<%= simple_form_for(@group, :html => {:class => 'form-horizontal'}) do |f| %>

	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.submit "Submit", :disable_with => "Submitting..." ,:class => "btn btn-primary" %>

<% end %>

app/views/groups/show.html.erb
<h3><%= @group.title %></h3>
<%= render template: "groups/_join_or_quit" %>
<hr/>
<% @post.each do |post| %>
	<p><%= post.content %></p>
	<% if current_user && post.editable_by?(current_user) %>
	<p><%= link_to "Edit", edit_group_post_path(post.group, post) %> | <%= link_to "Delete", group_post_path(post.group, post), method: :delete, data: { confirm: "Are you sure?"} %></p>
	<hr/>
	<% end %>
<% end %>
<% if current_user && current_user.is_member_of?(@group) %>
<%= link_to "New Post", new_group_post_path(@group), :class => "btn btn-primary" %>
<% end %>
<%= link_to "Back", groups_path, :class => "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to "Rails 101", groups_path, :class => "navbar-brand" %>
		</div>
	</div>
</nav>
<div style="margin-top:60px;">
<% if current_user %>
Logged in as <%= current_user.name %> | <%= link_to "sign out", destroy_user_session_path, method: :delete %> | <%= link_to "Profile", account_groups_path %>
<% else %>
<%= link_to "sign up", new_user_registration_path %> | <%= link_to "sign in", new_user_session_path %>
<% end %>
<% if flash.any? %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% end %>
</div>
<div class="container" style="padding-top: 10px">
	<%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
123

app/views/posts/edit.html.erb
<h3>Editing Post</h3>
<hr/>
<%= form_for [@group, @post] do |post| %>
	<p>Post: <%= post.text_field :content %></p>
	<p><%= post.submit "Update", :class => "btn btn-primary" %></p>
<% end %>

app/views/posts/new.html.erb
<h3>Creating New Post</h3>
<hr/>
<%= form_for [@group, @post] do |post| %>
	<p>Post: <%= post.text_field :content %></p>
	<p><%= post.submit "Post", :class => "btn btn-primary" %></p>
<% end %>